dev:
  model:
    name: "MTTS_CAN"
    weights_path: "./assets/models/mtts_can.h5"
    args:
      batch_size: 100
      frame_depth: 10
      nb_filters1: 32
      nb_filters2: 64
      input_shape: [36, 36, 3]

  bp_model:
    model_path: "./assets/models/lstm_ppg_nonmixed.h5"

prod:
  model:
    name: "MTTS_CAN"
    weights_path: "./assets/models/mtts_can.h5"
    args:
      batch_size: 100
      frame_depth: 10
      nb_filters1: 32
      nb_filters2: 64
      input_shape: [36, 36, 3]

  bp_model:
    model_path: "./assets/models/lstm_ppg_nonmixed.h5"
